import requests
import os

# The URL of your running Docker container
url = "http://127.0.0.1:8000/compile"

# Basic Typst code for a Resume Header
typst_code = """
#set page(paper: "us-letter", margin: 1cm)
#set text(font: "Liberation Sans", size: 11pt)

= John Doe
*Software Engineer* | github.com/johndoe

== Summary
This PDF was generated by your custom Resume Builder Engine. 
Phase 1 is complete!
"""

print("🚀 Sending request to Docker container...")

try:
    # Send the code to the Docker container
    response = requests.post(url, json={"code": typst_code})

    # Check if the container said "OK" (Status Code 200)
    if response.status_code == 200:
        output_filename = "phase1_success.pdf"
        
        # Save the binary data as a PDF file
        with open(output_filename, "wb") as f:
            f.write(response.content)
            
        print(f"✅ SUCCESS! PDF saved as '{output_filename}'")
        print("open this file to verify the content.")
    else:
        print(f"❌ FAILURE. Status Code: {response.status_code}")
        print("Error details:", response.text)

except Exception as e:
    print(f"❌ CONNECTION ERROR: {e}")
    print("Is your Docker container running? (docker run -p 8000:8000 resume-builder)")